version: 2

sources:
  - name: cafe
    database: cafe_db
    schema: public
    tables:
      - name: cafe_sales
        columns:
          - name: transaction_id
            tests:
              - not_null
              - unique

  - name: ops
    database: cafe_db
    schema: ops
    tables:
      - name: silver_corrections
        columns:
          - name: transaction_id
            tests:
              - not_null
              - unique
