version: 2

sources:
  - name: cafe
    database: cafe_db
    schema: public
    tables:
      - name: cafe_sales
        columns:
          - name: '"transaction id"'
            tests:
              - not_null
              - unique
          - name: '"transaction date"'
            tests:
              - not_null
          - name: '"price per unit"'
            tests:
              - not_null

  - name: ops
    database: cafe_db
    schema: ops
    tables:
      - name: silver_corrections
        columns:
          - name: transaction_id
            tests:
              - not_null
              - unique
